---
abstract: 'JSLint: The JavaScript Code Quality Tool (for JS)'
author:
  - 'Nick Patch <patch@cpan.org> is the packager of JS-JSLint'
  - 'Douglas Crockford <douglas@crockford.com> is the author of JSLint'
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JS-JSLint
provides:
  JS::JSLint:
    file: lib/JS/JSLint.pm
    version: 0.01
requires:
  JS: 0
  perl: v5.6.0
resources:
  bugtracker: https://github.com/patch/js-jslint-pm5/issues
  homepage: https://github.com/patch/js-jslint-pm5
  license: http://dev.perl.org/licenses/
  repository: https://github.com/patch/js-jslint-pm5.git
version: 0.01
